apiVersion: v1
kind: Service
metadata:
  name: todo-list-service
spec:
  selector:
    name: todo-list-pod
    app: todolist
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30001
  type: NodePort

